:relative-path: ../../../
include::{docdir}/variables.adoc[]

In this case, you want to use the login/password authentication for your users in your application.
You want to create a form to let your users to create their own account.
To do this, you only need to create your form and call the `signup()` method on the `DefaultStandardUserWorkflow` _cloud service_ when the user validate his form.

By default, the account creation need a user confirmation. To handle this on your application, you need to create a page that points on : _https://myappurl/account-confirmation/#/token_. When the user will click on the confirmation link, he will be redirected to this page.

.Sign up
====
We assume that we have a form that call the function `createAccount()` (of our _UserManagement_ class) at the submit action. Then we assume that a page has been created for the _account-confirmation_ URL.

NOTE: In `DefaultStandardUserWorkflow`, you just need to type the following informations to create an account : _username, email, password and passwordConfirmation_.

[source, javascript, linenums]
----
import { DefaultStandardUserWorkflow, UsernamePasswordAccountCreationDetails } from '@zetapush/platform';

class UserManagement {
  constructor(private userManagement: DefaultStandardUserWorkflow) { }

  createAccount(signupInfo: UsernamePasswordAccountCreationDetails) {
    // "signupInfo" regroups all necessary informations 
    this.userManagement.signup(signupInfo).then((account) => {
        // Do what you want with the created account
        // This account waiting the user confirmation
    });
  }
}
----

When the user submit his account creation form, `createAccount()` method is called and an account is created on the ZetaPush platform for this application.
By default, the account creation need a user confirmation. So an email has been sent to the user with a confirmation link.
When the user will click on the link, he will be redirected on the corresponding page.
====

